live_config_reload = true

[colors.normal]
black =  '#928374'
red  =   '#fb4934'
green =  '#b8bb26'
yellow = '#fabd2f'
blue  =  '#83a598'
magenta = '#d3869b'
cyan =    '#8ec07c'
white =  '#ebdbb2'

[colors.primary]
background = "#1d2021"
foreground = "#ebdbb2"

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.normal]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Regular"

[window]
decorations = "buttonless"
padding = { x = 4, y = 4 }
dynamic_padding = true
