live_config_reload = true

[colors.normal]
black =  '#928374'
red  =   '#ea6962'
green =  '#a9b665'
yellow = '#d8a657'
blue  =  '#7daea3'
magenta = '#d3869b'
cyan =    '#89b482'
white =  '#ebdbb2'

[colors.primary]
#background = "#1d2021"
background = "#000000"
#foreground = "#ebdbb2"
foreground = "#FFFFFF"

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.normal]
family = "BerkeleyMonoTrial Nerd Font"
style = "Regular"

[window]
decorations = "buttonless"
padding = { x = 2, y = 6 }
