#!/usr/bin/env sh

source "$HOME/.config/sketchybar/colors.sh"

PLUGIN_DIR="$CONFIG_DIR/plugins"

# TODO: Fix Berkeley font
# Needs to have Regular, Bold, Semibold, Heavy and Black variants
# FONT="BerkeleyMonoVariable Nerd Font" 
PADDINGS=3
RADIUS=8

bar=(
  position=top
  height=40
  margin=20
  y_offset=20
  corner_radius=$RADIUS
  border_color=$GREY
  border_width=1
  blur_radius=30
  color=$BLACK
)

sketchybar --bar "${bar[@]}"

default=(
  padding_left=5
  padding_right=5
  updates="when_shown"
  icon.font="Hack Nerd Font:Bold:17.0"
  # icon.font="$FONT:Bold:14.0"
  label.font="Hack Nerd Font:Bold:14.0"
  # label.font="$FONT:Semibold:13.0"
  icon.color=$ICON_COLOR
  label.color=$LABEL_COLOR
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
)

sketchybar --default "${default[@]}"

##### Adding Left Items #####
# We add some regular items to the left side of the bar, where
# only the properties deviating from the current defaults need to be set

sketchybar --add item chevron left \
           --set chevron icon= label.drawing=off \
           --add item front_app left \
           --set front_app script="$PLUGIN_DIR/front_app.sh" \
           --subscribe front_app front_app_switched

##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

# Some items refresh on a fixed cycle, e.g. the clock runs its script once
# every 10s. Other items respond to events they subscribe to, e.g. the
# volume.sh script is only executed once an actual change in system audio
# volume is registered. More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events

sketchybar --add item clock right \
           --set clock update_freq=10 icon=  script="$PLUGIN_DIR/clock.sh" \
           --add item volume right \
           --set volume script="$PLUGIN_DIR/volume.sh" \
           --subscribe volume volume_change \
           --add item battery right \
           --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
           --subscribe battery system_woke power_source_change

sketchybar --add event aerospace_workspace_change
  
for sid in $(aerospace list-workspaces --all); do
  set=(
    background.corner_radius=5
    background.height=20
    label.padding_left=0
    label.padding_right=10
    label="$sid"
    click_script="aerospace workspace $sid"
    script="$PLUGIN_DIR/aerospace.sh $sid"
  )

  sketchybar  --add item space.$sid left \
              --subscribe space.$sid aerospace_workspace_change \
              --set space.$sid "${set[@]}"
done

sketchybar --update
